# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toledo Bicycle Coalition
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Toledo Bicycle Coalition inspires people to bicycle and advocates for a city where everyone feels comfortable riding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toledobikeco.com" # the base hostname & protocol for your site
twitter_username: toledobikeco

# Build settings
markdown: kramdown
